pipeline {
    agent any
    
    tools {nodejs "node"}

    stages {
        stage('Clonar o repositorio') {
            steps {
                git branch: 'main', url: 'https://github.com/vhonorato/ebac.git'
            }
        }
        stage('Mudar de diretório') {
            steps {
                sh 'cd exercises/mod_16'
            }
        }
        stage('Instalar dependencias') {
            steps {
                sh 'npm install'
            }
        }
        stage('Executar testes') {
            steps {
                sh 'npm test'
            }
        }
    }
}